# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Allan Jiang
tagline:             'The blog'
description:         'Find me <a href="https://twitter.com/allan_jiang" target="_blank">@Allan_Jiang</a>. My words are my own.'
url:                 http://allanjsx@github.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Allan Jiang
  url:               https://twitter.com/allan_jiang
  email:             jiangshaoxiong18@gmail.com

# Custom vars
version:             1.0.0

# Gems
gems: [jekyll-paginate]
